<a href="https://colab.research.google.com/github/zzou19/mat494/blob/main/HW3_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [3]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [5]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [6]:
model.fit(x, y)

LogisticRegression(random_state=0, solver='liblinear')

In [7]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

LogisticRegression(multi_class='warn', random_state=0, solver='liblinear')

In [8]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x, y)

In [9]:
model.classes_

array([0, 1])

In [11]:
model.intercept_

array([-1.04608067])

In [12]:
model.coef_

array([[0.51491375]])

In [13]:
model.predict_proba(x)

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [14]:
model.predict(x)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [15]:
model.score(x, y)

0.9

In [16]:
confusion_matrix(y, model.predict(x))

array([[3, 1],
       [0, 6]])